// <auto-generated />
using System;
using Kyogo.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kyogo.Infrastructure.Migrations
{
    [DbContext(typeof(KyogoDbContext))]
    partial class KyogoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kyogo.Application.Authentication.Tokens.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires");

                    b.Property<string>("RawToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("raw_token");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Kyogo.Application.SpacedRepetition.Progress", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CardType")
                        .HasColumnType("integer")
                        .HasColumnName("card_type");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("Fluent")
                        .HasColumnType("boolean")
                        .HasColumnName("fluent");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("interval")
                        .HasColumnName("interval");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<TimeSpan?>("RetainedInterval")
                        .HasColumnType("interval")
                        .HasColumnName("retained_interval");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage");

                    b.Property<int?>("Step")
                        .HasColumnType("integer")
                        .HasColumnName("step");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.HasKey("Id")
                        .HasName("pk_progress_records");

                    b.ToTable("progress_records", (string)null);
                });

            modelBuilder.Entity("Kyogo.Application.Vocabulary.Modifications.TermModification", b =>
                {
                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("TermId", "OwnerId")
                        .HasName("pk_term_modifications");

                    b.ToTable("term_modifications", (string)null);
                });

            modelBuilder.Entity("Kyogo.Domain.Characters.Kanji", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string[]>("KunyoumiReadings")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("kunyoumi_readings");

                    b.Property<string[]>("Meanings")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("meanings");

                    b.Property<string[]>("OnyoumiReadings")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("onyoumi_readings");

                    b.HasKey("Id")
                        .HasName("pk_kanji");

                    b.ToTable("kanji", (string)null);
                });

            modelBuilder.Entity("Kyogo.Domain.Decks.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtworkPath")
                        .HasColumnType("text")
                        .HasColumnName("artwork_path");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("description");

                    b.Property<string[]>("Kanji")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("kanji");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid[]>("Terms")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("terms");

                    b.Property<string>("deck_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("deck_type");

                    b.HasKey("Id")
                        .HasName("pk_decks");

                    b.ToTable("decks", (string)null);

                    b.HasDiscriminator<string>("deck_type").HasValue("deck");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Kyogo.Domain.Decks.DeckSubscription", b =>
                {
                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid")
                        .HasColumnName("deck_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("DeckId", "UserId")
                        .HasName("pk_deck_subscriptions");

                    b.ToTable("deck_subscriptions", (string)null);
                });

            modelBuilder.Entity("Kyogo.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Kyogo.Domain.Vocabulary.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Components")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("components");

                    b.HasKey("Id")
                        .HasName("pk_terms");

                    b.ToTable("terms", (string)null);
                });

            modelBuilder.Entity("Kyogo.Domain.Decks.SubDeck", b =>
                {
                    b.HasBaseType("Kyogo.Domain.Decks.Deck");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.ToTable("decks", (string)null);

                    b.HasDiscriminator().HasValue("sub_deck");
                });

            modelBuilder.Entity("Kyogo.Application.Vocabulary.Modifications.TermModification", b =>
                {
                    b.OwnsMany("Kyogo.Application.Vocabulary.Modifications.Senses.SenseAddition", "SenseAdditions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("Common")
                                .HasColumnType("boolean")
                                .HasColumnName("common");

                            b1.Property<int>("InsertionIndex")
                                .HasColumnType("integer")
                                .HasColumnName("insertion_index");

                            b1.Property<string>("PartOfSpeech")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("part_of_speech");

                            b1.Property<string[]>("Tags")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("tags");

                            b1.Property<Guid>("TermModificationOwnerId")
                                .HasColumnType("uuid")
                                .HasColumnName("term_modification_owner_id");

                            b1.Property<Guid>("TermModificationTermId")
                                .HasColumnType("uuid")
                                .HasColumnName("term_modification_term_id");

                            b1.HasKey("Id")
                                .HasName("pk_sense_addition");

                            b1.HasIndex("TermModificationTermId", "TermModificationOwnerId")
                                .HasDatabaseName("ix_sense_addition_term_modification_term_id_term_modification_");

                            b1.ToTable("sense_addition", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TermModificationTermId", "TermModificationOwnerId")
                                .HasConstraintName("fk_sense_addition_term_modifications_term_modification_term_id");

                            b1.OwnsMany("Kyogo.Application.Vocabulary.Modifications.Glosses.CustomGloss", "Glosses", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<bool>("Primary")
                                        .HasColumnType("boolean")
                                        .HasColumnName("primary");

                                    b2.Property<Guid>("SenseAdditionId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("sense_addition_id");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("text");

                                    b2.HasKey("Id")
                                        .HasName("pk_custom_gloss");

                                    b2.HasIndex("SenseAdditionId")
                                        .HasDatabaseName("ix_custom_gloss_sense_addition_id");

                                    b2.ToTable("custom_gloss", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SenseAdditionId")
                                        .HasConstraintName("fk_custom_gloss_sense_addition_sense_addition_id");
                                });

                            b1.Navigation("Glosses");
                        });

                    b.OwnsMany("Kyogo.Application.Vocabulary.Modifications.Senses.SenseModification", "SenseModifications", b1 =>
                        {
                            b1.Property<Guid>("SenseId")
                                .HasColumnType("uuid")
                                .HasColumnName("sense_id");

                            b1.Property<bool?>("CommonOverride")
                                .HasColumnType("boolean")
                                .HasColumnName("common_override");

                            b1.Property<string>("PartOfSpeechOverride")
                                .HasColumnType("text")
                                .HasColumnName("part_of_speech_override");

                            b1.Property<string[]>("TagsOverride")
                                .HasColumnType("text[]")
                                .HasColumnName("tags_override");

                            b1.Property<Guid>("TermModificationOwnerId")
                                .HasColumnType("uuid")
                                .HasColumnName("term_modification_owner_id");

                            b1.Property<Guid>("TermModificationTermId")
                                .HasColumnType("uuid")
                                .HasColumnName("term_modification_term_id");

                            b1.HasKey("SenseId")
                                .HasName("pk_sense_modification");

                            b1.HasIndex("TermModificationTermId", "TermModificationOwnerId")
                                .HasDatabaseName("ix_sense_modification_term_modification_term_id_term_modificat");

                            b1.ToTable("sense_modification", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TermModificationTermId", "TermModificationOwnerId")
                                .HasConstraintName("fk_sense_modification_term_modifications_term_modification_ter");

                            b1.OwnsMany("Kyogo.Application.Vocabulary.Modifications.Glosses.GlossAddition", "GlossAdditions", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int>("InsertionIndex")
                                        .HasColumnType("integer")
                                        .HasColumnName("insertion_index");

                                    b2.Property<bool>("Primary")
                                        .HasColumnType("boolean")
                                        .HasColumnName("primary");

                                    b2.Property<Guid>("SenseModificationSenseId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("sense_modification_sense_id");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("text");

                                    b2.HasKey("Id")
                                        .HasName("pk_gloss_addition");

                                    b2.HasIndex("SenseModificationSenseId")
                                        .HasDatabaseName("ix_gloss_addition_sense_modification_sense_id");

                                    b2.ToTable("gloss_addition", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SenseModificationSenseId")
                                        .HasConstraintName("fk_gloss_addition_sense_modification_sense_modification_sense_");
                                });

                            b1.OwnsMany("Kyogo.Application.Vocabulary.Modifications.Glosses.GlossModification", "GlossModifications", b2 =>
                                {
                                    b2.Property<Guid>("ModifyGlossId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("modify_gloss_id");

                                    b2.Property<bool?>("PrimaryOverride")
                                        .HasColumnType("boolean")
                                        .HasColumnName("primary_override");

                                    b2.Property<Guid>("SenseModificationSenseId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("sense_modification_sense_id");

                                    b2.Property<string>("TextOverride")
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("text_override");

                                    b2.HasKey("ModifyGlossId")
                                        .HasName("pk_gloss_modification");

                                    b2.HasIndex("SenseModificationSenseId")
                                        .HasDatabaseName("ix_gloss_modification_sense_modification_sense_id");

                                    b2.ToTable("gloss_modification", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SenseModificationSenseId")
                                        .HasConstraintName("fk_gloss_modification_sense_modification_sense_modification_se");
                                });

                            b1.OwnsMany("Kyogo.Application.Vocabulary.Modifications.Glosses.GlossRemoval", "GlossRemovals", b2 =>
                                {
                                    b2.Property<Guid>("RemoveGlossId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("remove_gloss_id");

                                    b2.Property<Guid>("SenseModificationSenseId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("sense_modification_sense_id");

                                    b2.HasKey("RemoveGlossId")
                                        .HasName("pk_gloss_removal");

                                    b2.HasIndex("SenseModificationSenseId")
                                        .HasDatabaseName("ix_gloss_removal_sense_modification_sense_id");

                                    b2.ToTable("gloss_removal", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SenseModificationSenseId")
                                        .HasConstraintName("fk_gloss_removal_sense_modification_sense_modification_sense_id");
                                });

                            b1.Navigation("GlossAdditions");

                            b1.Navigation("GlossModifications");

                            b1.Navigation("GlossRemovals");
                        });

                    b.OwnsMany("Kyogo.Application.Vocabulary.Modifications.Senses.SenseRemoval", "SenseRemovals", b1 =>
                        {
                            b1.Property<Guid>("RemoveSenseId")
                                .HasColumnType("uuid")
                                .HasColumnName("remove_sense_id");

                            b1.Property<Guid>("TermModificationOwnerId")
                                .HasColumnType("uuid")
                                .HasColumnName("term_modification_owner_id");

                            b1.Property<Guid>("TermModificationTermId")
                                .HasColumnType("uuid")
                                .HasColumnName("term_modification_term_id");

                            b1.HasKey("RemoveSenseId")
                                .HasName("pk_sense_removal");

                            b1.HasIndex("TermModificationTermId", "TermModificationOwnerId")
                                .HasDatabaseName("ix_sense_removal_term_modification_term_id_term_modification_o");

                            b1.ToTable("sense_removal", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TermModificationTermId", "TermModificationOwnerId")
                                .HasConstraintName("fk_sense_removal_term_modifications_term_modification_term_id_");
                        });

                    b.Navigation("SenseAdditions");

                    b.Navigation("SenseModifications");

                    b.Navigation("SenseRemovals");
                });

            modelBuilder.Entity("Kyogo.Domain.Vocabulary.Term", b =>
                {
                    b.OwnsMany("Kyogo.Domain.Vocabulary.Senses.Sense", "Senses", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<bool>("Common")
                                .HasColumnType("boolean")
                                .HasColumnName("common");

                            b1.Property<string>("PartOfSpeech")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("part_of_speech");

                            b1.Property<string[]>("Tags")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("tags");

                            b1.Property<Guid>("TermId")
                                .HasColumnType("uuid")
                                .HasColumnName("term_id");

                            b1.HasKey("Id")
                                .HasName("pk_sense");

                            b1.HasIndex("TermId")
                                .HasDatabaseName("ix_sense_term_id");

                            b1.ToTable("sense", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TermId")
                                .HasConstraintName("fk_sense_terms_term_id");

                            b1.OwnsMany("Kyogo.Domain.Vocabulary.Glosses.Gloss", "Glosses", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<bool>("Primary")
                                        .HasColumnType("boolean")
                                        .HasColumnName("primary");

                                    b2.Property<Guid>("SenseId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("sense_id");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)")
                                        .HasColumnName("text");

                                    b2.HasKey("Id")
                                        .HasName("pk_gloss");

                                    b2.HasIndex("SenseId")
                                        .HasDatabaseName("ix_gloss_sense_id");

                                    b2.ToTable("gloss", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SenseId")
                                        .HasConstraintName("fk_gloss_sense_sense_id");
                                });

                            b1.Navigation("Glosses");
                        });

                    b.Navigation("Senses");
                });
#pragma warning restore 612, 618
        }
    }
}
